site_name: Unraid Integration
site_description: Documentation for the Unraid integration for Home Assistant
site_author: Ruaan Deysel
site_url: https://domalab.github.io/ha-unraid/

repo_url: https://github.com/domalab/ha-unraid
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Features: user-guide/features.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Advanced Usage:
    - Examples: advanced/examples.md
    - User Scripts: advanced/user-scripts.md
    - Docker Management: advanced/docker-management.md
    - VM Control: advanced/vm-control.md
  - Development:
    - Contributing: development/contributing.md
  - Project:
    - Changelog: https://github.com/domalab/ha-unraid/blob/main/CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/domalab/ha-unraid
