force_update:
  name: Force Update
  description: Force an immediate update of Unraid data.
  fields:
    config_entry:
      name: Config Entry ID
      description: The ID of the config entry to update. If not provided, all Unraid instances will be updated.
      example: "1234abcd5678efgh"
      required: false
      selector:
        text:

execute_command:
  name: Execute Command
  description: Execute a command on the Unraid server.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    command:
      name: Command
      description: The command to execute on the Unraid server.
      example: "ls -l /mnt/user/"
      required: true
      selector:
        text:

execute_in_container:
  name: Execute in Container
  description: Execute a command in a Docker container on the Unraid server.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    container:
      name: Container Name
      description: The name of the Docker container to execute the command in.
      example: "my-container"
      required: true
      selector:
        text:
    command:
      name: Command
      description: The command to execute in the Docker container.
      example: "ls -l /app/"
      required: true
      selector:
        text:
    detached:
      name: Detached
      description: Whether to run the command in detached mode.
      required: false
      default: false
      selector:
        boolean:

execute_user_script:
  name: Execute User Script
  description: Execute a user script on the Unraid server.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    script_name:
      name: Script Name
      description: The name of the user script to execute.
      example: "my_script.sh"
      required: true
      selector:
        text:
    background:
      name: Run in Background
      description: Whether to run the script in the background.
      required: false
      default: false
      selector:
        boolean:

stop_user_script:
  name: Stop User Script
  description: Stop a running user script on the Unraid server.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    script_name:
      name: Script Name
      description: The name of the user script to stop.
      example: "my_script.sh"
      required: true
      selector:
        text:

system_reboot:
  name: Reboot System
  description: >-
    Reboot the Unraid system. This operation will fail if there are running VMs
    or active file operations. Running Docker containers will be stopped.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    delay:
      name: Delay
      description: >-
        Delay in seconds before executing the reboot (0-3600).
        This allows time for running operations to complete.
      default: 0
      required: false
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

system_shutdown:
  name: Shutdown System
  description: >-
    Shutdown the Unraid system. This operation requires the array to be stopped first
    and will fail if there are running VMs or active file operations.
    Running Docker containers will be stopped.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    delay:
      name: Delay
      description: >-
        Delay in seconds before executing the shutdown (0-3600).
        This allows time for running operations to complete.
      default: 0
      required: false
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

get_optimization_stats:
  name: Get Optimization Stats
  description: >-
    Get statistics about the optimization components, including cache usage
    and sensor prioritization metrics.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:

clear_cache:
  name: Clear Cache
  description: >-
    Clear the cache used by the integration. This can help if you're experiencing
    stale data or want to force fresh data to be loaded.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    prefix:
      name: Cache Prefix
      description: >-
        Optional prefix to clear only specific cache items. Leave empty to clear
        the entire cache. Examples: "system_stats", "array_state", "vms".
      required: false
      default: ""
      example: "system_stats"
      selector:
        text:

force_sensor_update:
  name: Force Sensor Update
  description: >-
    Force an immediate update of a specific sensor regardless of its
    normal update schedule.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    sensor_id:
      name: Sensor ID
      description: >-
        The ID of the sensor to update. Examples: "cpu_usage", "array_status",
        "network_eth0", "vm_windows10", etc.
      required: true
      example: "cpu_usage"
      selector:
        text:

# Docker container services
docker_pause:
  name: Pause Docker Container
  description: Pause a running Docker container.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    container:
      name: Container Name
      description: The name of the Docker container to pause.
      example: "my-container"
      required: true
      selector:
        text:

docker_resume:
  name: Resume Docker Container
  description: Resume a paused Docker container.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    container:
      name: Container Name
      description: The name of the Docker container to resume.
      example: "my-container"
      required: true
      selector:
        text:

docker_restart:
  name: Restart Docker Container
  description: Restart a Docker container.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    container:
      name: Container Name
      description: The name of the Docker container to restart.
      example: "my-container"
      required: true
      selector:
        text:

# VM services
vm_pause:
  name: Pause VM
  description: Pause a running virtual machine.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    vm:
      name: VM Name
      description: The name of the virtual machine to pause.
      example: "Windows10"
      required: true
      selector:
        text:

vm_resume:
  name: Resume VM
  description: Resume a paused virtual machine.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    vm:
      name: VM Name
      description: The name of the virtual machine to resume.
      example: "Windows10"
      required: true
      selector:
        text:

vm_restart:
  name: Restart VM
  description: Restart a running virtual machine.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    vm:
      name: VM Name
      description: The name of the virtual machine to restart.
      example: "Windows10"
      required: true
      selector:
        text:

vm_hibernate:
  name: Hibernate VM
  description: Hibernate a running virtual machine (suspend to disk).
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    vm:
      name: VM Name
      description: The name of the virtual machine to hibernate.
      example: "Windows10"
      required: true
      selector:
        text:

vm_force_stop:
  name: Force Stop VM
  description: Force stop a virtual machine. This is equivalent to pulling the power plug and should only be used when normal shutdown fails.
  fields:
    entry_id:
      name: Config Entry ID
      description: The ID of the config entry for the Unraid instance.
      example: "1234abcd5678efgh"
      required: true
      selector:
        text:
    vm:
      name: VM Name
      description: The name of the virtual machine to force stop.
      example: "Windows10"
      required: true
      selector:
        text: