# Cloudflare Pages configuration
[build]
  command = "./cloudflare-build.sh"
  publish = "docs/_site"

[build.environment]
  RUBY_VERSION = "3.3.0"
  JEKYLL_ENV = "production"
  SKIP_PYTHON_DEPENDENCIES = "true"