# Site settings
title: "Unraid Integration Documentation"
description: "Documentation for the Unraid integration for Home Assistant"
baseurl: "" # the subpath of your site
url: "https://ha-unraid.pages.dev" # CloudFlare Pages domain

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
search_enabled: true

# Theme settings
color_scheme: light
heading_anchors: true
nav_sort: case_sensitive

# Collections
collections:
  content:
    permalink: "/:collection/:path/"
    output: true

# Just the Docs settings
aux_links:
  "GitHub Repository":
    - "https://github.com/domalab/ha-unraid"

# Google AdSense
google_adsense_id: "ca-pub-7358189775686770"

# CloudFlare Pages specific settings
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# SEO settings
twitter:
  username: unraidapi
  card: summary_large_image
social:
  name: Unraid Integration
  links:
    - https://github.com/domalab/ha-unraid

# Performance settings
compression: true

# Include files that would otherwise be ignored
include:
  - ads.txt

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
