name: Python Linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Python Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint mypy types-aiofiles
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 custom_components/unraid --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run pylint
        run: |
          pylint custom_components/unraid

      - name: Run mypy
        run: |
          echo "Skipping mypy checks for now"
          # mypy custom_components/unraid
