name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 2025.04.09)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (markdown format)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update version in manifest.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ github.event.inputs.version }}"/' custom_components/unraid/manifest.json

      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/unraid/manifest.json
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin main --tags

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: |
            # Release ${{ github.event.inputs.version }}

            ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
